name: ESLint
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - '*'
            - '!docs'
            - '!gh-pages'
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    test:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node v18
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build
              run: yarn build

            - name: Run ESLint
              run: yarn lint

            - name: Run TSC
              run: yarn build:check
